### ISSUE TITLE
Landing page static

### ISSUE THREAD

**Issue by faris114** [facn5/Yoyo#43]
make a landing page witch will contain two buttons sign up sign in

**Comment by misterrodger** [comment]
![2471e11f-58d8-4260-b739-ef5fc967187b_200x200](https://user-images.githubusercontent.com/32282170/57692009-5cebe180-764e-11e9-820e-d30478d75e7a.png)

**Comment by misterrodger** [comment]
![yoyo-logo1](https://user-images.githubusercontent.com/32282170/57733684-01464600-7698-11e9-89e7-b9debad0bee0.png)

**Comment by misterrodger** [comment]
![yoyo-title](https://user-images.githubusercontent.com/32282170/57733693-073c2700-7698-11e9-8b44-a8919483d984.png)

**Comment by misterrodger** [comment]
![yoyo-balloons](https://user-images.githubusercontent.com/32282170/57733708-0dca9e80-7698-11e9-923d-1bd24a20a858.png)
