### ISSUE TITLE
Components

### ISSUE THREAD

**Issue by misterrodger** [facn5/Yoyo#57]
![IMG_20190513_142548206](https://user-images.githubusercontent.com/32282170/57648144-5ff2bd80-75cd-11e9-95c3-b9b037b4dc4e.jpg)

**Comment by misterrodger** [comment]
Signup form component and functional.  I completed the create-event form as well since they are so similar (took 15 minutes).

Faris is working on landing page sign-in component

**Comment by mrfong** [comment]
Going to be working on building the main components (Header,Navbar,Filter..etc)
